#!/bin/bash
if [ "$2" = "off" ];
then
DEVICE_IP=$1 node poweroff.js
fi
if [ "$2" = "on" ];
then
DEVICE_IP=$1 node poweron.js
fi
if [ "$2" = "mute" ];
then
DEVICE_IP=$1 node mute.js
fi
if [ "$2" = "unmute" ];
then
DEVICE_IP=$1 node unmute.js
fi
if [ "$2" = "vol" ];
then
DEVICE_IP=$1 node volume.js $3
fi
if [ "$1" = "notify" ];
then
python quickstart.py
fi
if [ "$1" = "info" ];
then
nanodlna list
fi
if [ "$1" = "play" ];
then 
python play.py
fi
if [ "$1" = "help" ];
then
echo "usage"
echo "info - to get the info of api ./index info"
echo "play - to play the song ./index play"
echo "on - to on the device ./index <ipaddress> on"
echo "off - to off the device ./index <ipaddress> off"
echo "mute - to mute the device ./index <ipaddress> mute"
echo "unmute - to unmute the device ./index <ipaddress> unmute"
echo "vol - to control the volume ./index <ipaddress> vol <value>"
echo "notify to use notifiction functionality ./index notify"
fi
